services:
  postgres:
    image: postgres:15.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aligned-api
    ports:
      - "8085:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aligned-frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - api

volumes:
  postgres_data:
